package com.yinshan.happycash.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "CALL_LOG".
 */
@Entity
public class CallLog {

    @Id(autoincrement = true)
    private Long id;
    private String name;

    @NotNull
    private String number;
    private Integer type;
    private String date;
    private Long duration;
    private Integer state;
    private Integer flag;

    @Generated
    public CallLog() {
    }

    public CallLog(Long id) {
        this.id = id;
    }

    @Generated
    public CallLog(Long id, String name, String number, Integer type, String date, Long duration, Integer state, Integer flag) {
        this.id = id;
        this.name = name;
        this.number = number;
        this.type = type;
        this.date = date;
        this.duration = duration;
        this.state = state;
        this.flag = flag;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @NotNull
    public String getNumber() {
        return number;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNumber(@NotNull String number) {
        this.number = number;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public Long getDuration() {
        return duration;
    }

    public void setDuration(Long duration) {
        this.duration = duration;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public Integer getFlag() {
        return flag;
    }

    public void setFlag(Integer flag) {
        this.flag = flag;
    }

}
