package com.yinshan.happycash.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yinshan.happycash.dao.Location;
import com.yinshan.happycash.dao.Contact;
import com.yinshan.happycash.dao.Event;
import com.yinshan.happycash.dao.CallLog;
import com.yinshan.happycash.dao.Message;

import com.yinshan.happycash.dao.LocationDao;
import com.yinshan.happycash.dao.ContactDao;
import com.yinshan.happycash.dao.EventDao;
import com.yinshan.happycash.dao.CallLogDao;
import com.yinshan.happycash.dao.MessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig locationDaoConfig;
    private final DaoConfig contactDaoConfig;
    private final DaoConfig eventDaoConfig;
    private final DaoConfig callLogDaoConfig;
    private final DaoConfig messageDaoConfig;

    private final LocationDao locationDao;
    private final ContactDao contactDao;
    private final EventDao eventDao;
    private final CallLogDao callLogDao;
    private final MessageDao messageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        locationDaoConfig = daoConfigMap.get(LocationDao.class).clone();
        locationDaoConfig.initIdentityScope(type);

        contactDaoConfig = daoConfigMap.get(ContactDao.class).clone();
        contactDaoConfig.initIdentityScope(type);

        eventDaoConfig = daoConfigMap.get(EventDao.class).clone();
        eventDaoConfig.initIdentityScope(type);

        callLogDaoConfig = daoConfigMap.get(CallLogDao.class).clone();
        callLogDaoConfig.initIdentityScope(type);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        locationDao = new LocationDao(locationDaoConfig, this);
        contactDao = new ContactDao(contactDaoConfig, this);
        eventDao = new EventDao(eventDaoConfig, this);
        callLogDao = new CallLogDao(callLogDaoConfig, this);
        messageDao = new MessageDao(messageDaoConfig, this);

        registerDao(Location.class, locationDao);
        registerDao(Contact.class, contactDao);
        registerDao(Event.class, eventDao);
        registerDao(CallLog.class, callLogDao);
        registerDao(Message.class, messageDao);
    }
    
    public void clear() {
        locationDaoConfig.clearIdentityScope();
        contactDaoConfig.clearIdentityScope();
        eventDaoConfig.clearIdentityScope();
        callLogDaoConfig.clearIdentityScope();
        messageDaoConfig.clearIdentityScope();
    }

    public LocationDao getLocationDao() {
        return locationDao;
    }

    public ContactDao getContactDao() {
        return contactDao;
    }

    public EventDao getEventDao() {
        return eventDao;
    }

    public CallLogDao getCallLogDao() {
        return callLogDao;
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

}
