package com.yinshan.happycash.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "EVENT".
 */
@Entity
public class Event {

    @Id(autoincrement = true)
    private Long id;
    private String eventId;
    private String eventTime;

    @Generated
    public Event() {
    }

    public Event(Long id) {
        this.id = id;
    }

    @Generated
    public Event(Long id, String eventId, String eventTime) {
        this.id = id;
        this.eventId = eventId;
        this.eventTime = eventTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEventId() {
        return eventId;
    }

    public void setEventId(String eventId) {
        this.eventId = eventId;
    }

    public String getEventTime() {
        return eventTime;
    }

    public void setEventTime(String eventTime) {
        this.eventTime = eventTime;
    }

}
