package com.yinshan.happycash.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "LOCATION".
 */
@Entity
public class Location {

    @Id(autoincrement = true)
    private Long id;
    private Integer locType;
    private Double latitude;
    private Double longitude;
    private Double altitude;
    private String dateTime;

    @Generated
    public Location() {
    }

    public Location(Long id) {
        this.id = id;
    }

    @Generated
    public Location(Long id, Integer locType, Double latitude, Double longitude, Double altitude, String dateTime) {
        this.id = id;
        this.locType = locType;
        this.latitude = latitude;
        this.longitude = longitude;
        this.altitude = altitude;
        this.dateTime = dateTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getLocType() {
        return locType;
    }

    public void setLocType(Integer locType) {
        this.locType = locType;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public Double getAltitude() {
        return altitude;
    }

    public void setAltitude(Double altitude) {
        this.altitude = altitude;
    }

    public String getDateTime() {
        return dateTime;
    }

    public void setDateTime(String dateTime) {
        this.dateTime = dateTime;
    }

}
